name: 💡 Предложение / Improvement
description: Предложить улучшение или идею
title: "[IDEA]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Опишите идею, улучшение или пожелание.
        Формат свободный.

  - type: textarea
    id: idea
    attributes:
      label: Описание предложения
      placeholder: |
        Что хотите улучшить?
        Почему это будет полезно?
        Есть ли примеры?
    validations:
      required: true
