on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Executing remote ssh command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH }}
          script: |
            echo "Stoping old version"
            if [ -d ~/parser_avito ];
            then
                cd ~/parser_avito
                make stop
            fi

            echo "Removing old version"
            cd ~
            rm -rf parser_avito
            # yes | sudo docker system prune -a

            echo "Pulling new version"
            GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" git clone git@github.com:altservices/parser_avito.git

            # echo "Copying keys"
            # cp ~/.secrets/parser_avito.env ~/parser_avito/.env

            echo "Starting new version"
            cd ~/parser_avito
            make run
